services:
    _defaults:
        autowire: true
        autoconfigure: false

    Disjfa\MenuBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests,DependencyInjection}'

    Disjfa\MenuBundle\Menu\AdminMenuBuilder:
        tags:
        - { name: 'knp_menu.menu_builder', method: 'build', alias: 'admin' }

    Disjfa\MenuBundle\Menu\SiteMenuBuilder:
        tags:
        - { name: 'knp_menu.menu_builder', method: 'build', alias: 'site' }

